### ISSUE TITLE
Package has dependencies on GitHub

### ISSUE THREAD

**Issue by anselmstordeur** [rxaviers/async-pool#3] opened 2018-10-22 14:19 UTC
`assert` is pulled from GitHub which is a performance issue on some of my systems. Additonally you need git on all machines that want to use your package.

It would be great if the assert module can be pulled from npm instead of GitHub. There are many assert library on npm. Maybe you could choose one that is already on npm?

**Comment by rxaviers** [comment] 2018-10-22 19:37
Thanks for filing this issue. I'd like to understand your concern in a little more detail please. Note this is only needed/used on development. Is it about installation time or runtime? Thanks

**Comment by anselmstordeur** [comment] 2018-10-23 11:30
If it is only used in development you could just install it as an devDependency. It is currently installed as a normal dependency and gets installed by default if someone depends on `tiny-async-pool`.

The problem I have is git specific, but I don't want to use git for npm module resolution. If I install `tiny-async-pool` npm tries to install `assertion` module from your GitHub account (using git). This is uneccesary.

I work with Docker and try to keep my Images as small as possible so I don't want to install git if it is not necessary.

**Comment by anselmstordeur** [comment] 2018-10-23 11:30
Is is only about installation

**Comment by rxaviers** [comment] 2018-10-23 11:51
Thanks for the clarification, I understand your problem now. On each deployed server, you run `npm install` and installing the extra `assertion` module from github impacts your install time.

Why can't we make `assertion` a `devDependency`? Because, it's an actual dependency (that can be avoided user's staging/production environment). Note the difference between user's dependencies (i.e., `dependencies`) and `async-pool` development dependencies (i.e., `devDependencies`, e.g., `mocha`).

Why can't we use node's internal `assert`? Because what I have in `assertion` is actually a higher level abstraction. If we change `assertion` to use node's internal `assert` under the hoods we would still need to install it.

What can we do? I assume your application has dozen other dependencies and the problem is that `assertion` comes from github instead of npm. Would publishing `assertion` in npm (as regular package) instead of relying on github solve your problem?

Thanks

**Comment by anselmstordeur** [comment] 2018-10-23 12:05
Publishing `assertion` would be great and would solve my problem, but you would have to change the package name, because `assertion` is already used by another package.

**Comment by rxaviers** [comment] 2018-10-23 13:49
Done, that module was named `yaassertion`. New version released `1.0.2`.

Fixed by ad1489a79f6e0fe0e13f873920d6b8469e2f51cb

**Comment by rxaviers** [comment] 2018-10-23 13:50
Please, let me know if you find any problems

**Closed as completed by rxaviers** 2018-10-23 13:49 UTC

**Comment by anselmstordeur** [comment] 2018-10-23 14:27
Thank you.

**Comment by anselmstordeur** [comment] 2018-10-23 14:34
The package `yaasertion` is not published on npm. `tiny-async-pool@1.0.2` cannot be installed....

**Comment by rxaviers** [comment] 2018-10-23 14:45
My bad, I published to a wrong npm registry. Re-did it now https://www.npmjs.com/package/yaassertion, please can you check?

**Comment by anselmstordeur** [comment] 2018-10-23 14:52
Now it works. Thank you.
